<div class="ma-body-wrapper">
	<div class="container-fluid">
		<div class="body-wrapper">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12 col-md-offset-2 ">
					<?php  echo $this->getLayout()->createBlock('banner7/banner7')->setTemplate('magentothem/banner7/banner7.phtml')->toHtml(); ?>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12">
					<?php  echo $this->getLayout()->createBlock('timer/timer')->setTemplate('magentothem/timer/timer.phtml')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="top-content">
	<div class="container-fluid">
		<div class="row">
			<div class=" col-lg-2 col-md-3 col-sm-12 ">
				<?php  echo $this->getLayout()->createBlock('mostviewedproductslider/mostviewedproductslider')->setTemplate('magentothem/mostviewedproductslider/mostviewedproductslider.phtml')->toHtml(); ?>
				<?php  echo $this->getLayout()->createBlock('blog/menu_sidebar')->setTemplate('magentothem_blog/blog_slide.phtml')->toHtml(); ?>
			</div>
			<div class=" col-lg-10 col-md-9 col-sm-12 ">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('ma_block_static_1')->toHtml() ?>
				<?php  echo $this->getLayout()->createBlock('producttabs/producttabs')->setTemplate('magentothem/producttabs/producttabs.phtml')->toHtml(); ?>
			</div>
			
		</div>
	</div>
</div>
