<?php
$enabled = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/enabled');
if($enabled):

$title = $this->getTitle();
$identify = $this->getIdentify();
$categoryIds = $this->getCatIds();
$categoryIds = explode(',', $categoryIds);
$_helper = $this->helper('catalog/output');
$productsOnRow = $this->getProductsOnRow();
if(!$productsOnRow) $productsOnRow = 3;
if ( !$this->getWidthThumbnail() ){
	$w_thumbnail = 135;
} else {
	$w_thumbnail = $this->getWidthThumbnail();
}
if( !$this->getHeightThumbnail() ){
	$h_thumbnail = 135;
 }
else {
	$h_thumbnail = $this->getHeightThumbnail();
}
?>

<?php
		$itemsDefault = $this->getItemsDefault();
		$itemsDesktop = $this->getItemsDesktop();
		$itemsDesktopSmall = $this->getItemsDesktopSmall();
		$itemsTablet = $this->getItemsTablet();
		$itemsMobile = $this->getItemsMobile();
		$max_shortcontent = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/short_content');
        $speed = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/speed');
        $nav_ctrl = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/nav_ctrl');
        $next_back = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/next_back');
        $show_price = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/show_price');
        $review = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/show_review');
        $addtocart = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/addtocart');
        $addtowishlist = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/addtowishlist');
        $addtocompare = Mage::getStoreConfig('catthumbnailslider/catthumbnailslider_config/addtocompare');
        $rows = $this->getRowShow();
		$title = $this->getTitle();
?>
<div class="catthumbnailslider">
	<div class="ma-title"><?php echo '<h2>'.$title.'</h2>'; ?></div>
  <ul class="tabs catthumb-tabs<?php echo '-'.$identify;?>  tab_categorys"> 
   <?php 
	$k = 0;
	foreach($categoryIds as $cate_id) {
		$cate_model = Mage::getModel('catalog/category');
		$cate_ojb = $cate_model->load($cate_id);
		$cateName = $cate_model->load($cate_id)->getName();
		
		if($cateName) {
			
   ?>
			<li class="<?php if($k==0){ echo "active"; }?>">
				<div class="catthumb-tab<?php echo $cate_id.'-'.$identify;?>">
					<?php if($cate_ojb->getCatThumbnail()): ?>
						<img class="catthumb_hover" src="<?php echo $this->getCatHoverImage($cate_id); ?>" alt="<?php echo $cateName; ?>"/>
						<span class="catthumb_hover"><?php echo $cateName; ?></span>
					<?php else: ?>
						<span class="catthumb_hover"><?php echo $cateName; ?></span>
					<?php endIf; ?>
				</div>
			</li>
	<?php }  $k++; } ?>
    </ul>

	<div class="tab_container"> 
		<?php foreach($categoryIds as $cate_id) {
		?>
		 <div id="catthumb-tab<?php echo $cate_id.'-'.$identify;?>" class="catthumb_tab_content_<?php echo $identify; ?>"> 
			<?php $_productCollection = $this->getProductCate($cate_id); ?>
			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $productsOnRow; ?>
		<div class="row">	
		<ul class="owl catthumbnailslider-owl">	
		<?php $i=0; foreach ($_productCollection as $_product): ?>
				<?php if($i %$rows == 0) echo "<li class='catthumbnailslider-item'>"; ?>
				<div class="item-inner">
					<div class="ma-box-content">
						<?php
						 $newFromDate = $_product->getNewsFromDate();
						 $newToDate = $_product->getNewsToDate();                 
						 $now = date("Y-m-d H:m(worry)");
						 // Get the Special Price
						 $specialprice = $_product->getSpecialPrice(); 
						 // Get the Special Price FROM date
						 $specialPriceFromDate = $_product->getSpecialFromDate();
						 // Get the Special Price TO date
						 $specialPriceToDate = $_product->getSpecialToDate();
						 // Get Current date
						 if ($specialprice&&(($specialPriceFromDate <= $now && $specialPriceToDate >= $now) || (($specialPriceFromDate <= $now && $specialPriceFromDate != NULL) && $specialPriceToDate  == ''))&& Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label')){
							$_savePercent = 100 - round(($_product->getSpecialPrice() / $_product->getPrice())*100);
							echo "<span class='hot-sale'>-".$_savePercent."%<small>Off</small></span>";
						 }else{
						  if((($newFromDate <= $now && $newToDate >= $now) || (($newFromDate <= $now && $newFromDate != NULL) && $newToDate == NULL)) && Mage::getStoreConfig('themeoptions/themeoptions_config/new_label') ) {
						 ?>
							 <div class="label-pro-new"><span><?php echo $this->__('new') ?></span></div>
						 <?php
						  }
						 }
						?>
					
						<div class="products clearfix">
							 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
							  <span class="product-image">
							   <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail,$h_thumbnail); ?>" width="$w_thumbnail" height="$h_thumbnail" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							  </span>
							  <span class="product-image image-rotator">
							   <?php 
							   $product = $_product;
							   if ($product->getRotatorImage() && $product->getRotatorImage() !='no_selection') {
								//$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
								$image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize($w_thumbnail, $h_thumbnail);
							   } else {
								$image = Mage::helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail);
							   }
							   ?>
							   <img src="<?php echo $image ?>" width="$w_thumbnail" height="$h_thumbnail" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							   </span>   
							</a>
							
							<div class="actions">
							<?php  if($addtowishlist || $addtocompare): ?>
								<ul class="add-to-links">
									<?php if($addtowishlist): ?>
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist fa fa-heart"><span><?php echo $this->__('Add to Wishlist') ?></span></a></li>
										<?php endif; ?>
									<?php endif; ?>
									<?php if($addtocompare): ?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare fa fa-retweet"><span><?php echo $this->__('Add to Compare') ?></span></a></li>
										<?php endif; ?>
									<?php endif; ?>
								</ul>
							<?php endif; ?>
							
							<?php if($addtocart): ?>
								<?php if($_product->isSaleable()): ?>
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart fa fa-shopping-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
							<?php endif; ?>
						</div>
						<?php $i++;?>
							
						</div>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<?php if($review) { ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						<?php } ?>
						<?php 
						if($show_price)
							{ 
						?>
						<div class="price-box">
							<?php
							$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
							$price = $_product->getPrice();
							$specialprice = $_product->getFinalPrice();
							if($price != $specialprice){
							if($price != ''){
							echo '<p class="old-price"><span class="price-label">';
							echo $this->__('Regular Price'). ': </span>';
							echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p>';
							}
							if($specialprice != '')
							{
							echo '<p class="special-price">
							<span class="price-label">Special Price</span>
							<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
							</p> ';
							} 
							}else {
							echo '<div class="price-boxs">
							<span class="regular-price">
							<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
							</span>    
							</div>';    
							}
							?>
						</div>
						<?php 
							} 
						?>
						
					</div>
				</div>
				<?php if($i %$rows == 0) echo "</li>"; ?>                   
			<?php endforeach; ?>
				<?php if($i %$rows != 0) echo "</li>"; ?>
				
		</ul>
		</div>
			<script type="text/javascript">
				$jq(document).ready(function(){
					<?php $idBx = '#catthumb-tab'.$cate_id.'-'.$identify.' .owl'; ?>
					$jq("<?php echo $idBx; ?>").owlCarousel({
						autoPlay : false,
						items : <?php if($itemsDefault) echo $itemsDefault; else echo '5'; ?>,
						itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
						itemsDesktopSmall : [980,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
						itemsTablet: [768,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
						itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
						slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
						stopOnHover : true,
						pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
						scrollPerPage:true,
					});
					
					$jq(".tab_categorys").owlCarousel({
						autoPlay : false,
						items : 7,
						itemsDesktop : [1199,5],
						itemsDesktopSmall : [980,4],
						itemsTablet: [768,3],
						itemsMobile : [479,1],
						slideSpeed : 500,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : true,
						stopOnHover : true,
						pagination : false,
						scrollPerPage:true,
					});
				});
			</script>
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 

</div> <!-- #container -->

<script type="text/javascript">

$jq(document).ready(function() {
	
	$jq(".catthumb_tab_content_<?php echo $identify; ?>").hide();
	$jq(".catthumb_tab_content_<?php echo $identify; ?>:first").show(); 

	$jq("ul.catthumb-tabs<?php echo '-'.$identify;?> li").click(function() {
		$jq("ul.catthumb-tabs<?php echo '-'.$identify;?> li").removeClass("active");
		$jq(this).addClass("active");
		$jq(".catthumb_tab_content_<?php echo $identify; ?>").hide();
		var activeTab = $jq(this).find("div").attr('class'); 
		$jq("#"+activeTab).fadeIn(); 
	});
});

</script> 
<?php endif; ?>