<?php
$title = $this->getTitle();
$identify = $this->getIdentify();
$categoryIds = $this->getCatIds();
$categoryIds = explode(',', $categoryIds);
$_helper = $this->helper('catalog/output');
$productsOnRow = $this->getProductsOnRow();
if(!$productsOnRow) $productsOnRow = 3;
if ( !$this->getWidthThumbnail() ){
	$w_thumbnail = 135;
} else {
	$w_thumbnail = $this->getWidthThumbnail();
}
if( !$this->getHeightThumbnail() ){
	$h_thumbnail = 135;
 }
else {
	$h_thumbnail = $this->getHeightThumbnail();
}
?>

<?php
		$itemsDefault = $this->getItemsDefault();
		$itemsDesktop = $this->getItemsDesktop();
		$itemsDesktopSmall = $this->getItemsDesktopSmall();
		$itemsTablet = $this->getItemsTablet();
		$itemsMobile = $this->getItemsMobile();
        $speed = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/speed');
        $nav_ctrl = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/nav_ctrl');
        $next_back = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/next_back');
        $show_price = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/show_price');
        $review = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/show_review');
		$addtocart = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtocart');
        $addtowishlist = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtowishlist');
        $addtocompare = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtocompare');
        $rows = $this->getRowShow();
		$title = $this->getTitle();
?>
<div class="category-slider-container">
	<div class="category-tab-title">
		<?php 	echo '<h2>'.$title.'</h2>'; ?>
	</div>
  <ul class="tabs tabs<?php echo '-'.$identify;?>  tab_categorys"> 
   <?php 
	$k = 0;
	foreach($categoryIds as $cate_id) {
		$cate_model = Mage::getModel('catalog/category');
		$cateName = $cate_model->load($cate_id)->getName();
		
		if($cateName) {
   ?>
			<li class="<?php if($k==0){ echo "active"; }?>"><p class="tab<?php echo $cate_id.'-'.$identify;?>"><?php  echo $cateName; ?></p></li>
	<?php }  $k++; } ?>
    </ul>

	<div class="tab_container"> 
		<?php foreach($categoryIds as $cate_id) {
		?>
		 <div id="tab<?php echo $cate_id.'-'.$identify;?>" class="tab_content_<?php echo $identify; ?>"> 
			<?php $_productCollection = $this->getProductCate($cate_id); ?>
			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $productsOnRow; ?>
		<div class="row">
			
				<?php $category = Mage::getModel('catalog/category')->load($cate_id); ?>
				<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
					<div class="list-subbcategories">
						<h2><a href="<?php echo $category->getUrl(); ?>"><i class="fa fa-check"></i><?php echo $this->__('View All Category')?></a></h2>
						<?php
							$children = Mage::getModel('catalog/category')->getCategories($cate_id);
							echo '<ul>';
							$c = 0; $li_po = "";
							foreach ($children as $cate) {
								$c++;
								if($c % 2 == 0) {
									$li_po = "even";
								} else {
									$li_po = "odd";
								}
								$cate = Mage::getModel('catalog/category')->load($cate->getId());
								echo '<li class="sub-cate-'. $li_po .' sub-category-'.$cate->getId().'" ><a href="'.$cate->getUrl().'">'.$cate->getName().'</a></li>';
							}
							$c = 0;
							echo '</ul>';
						?>
					</div>
				</div>
				<div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
					<div class="row">
						<div class="hidden-xs">
							<div class="thum-image">
								<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$category->getThumbnail() ?>" alt="<?php echo $category->getName() ?>"/>
							</div>
						</div>
						<div class="productCategory">
							<div class="row">
								<ul class="owl">	
								<?php $i=0; foreach ($_productCollection as $_product): ?>
								<?php if($i %$rows == 0) echo "<li class='categorytab-item'>"; ?>
									<div class="item-inner">
										<div class="ma-box-content"> 
											<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
											<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
											<?php if($review) { ?>
											<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
											<?php } ?>
											<?php if($show_price): ?>
												<div class="price-box">
													<?php
													$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
													$price = $_product->getPrice();
													$specialprice = $_product->getFinalPrice();
													if($price != $specialprice){
													if($price != ''){
													echo '<p class="old-price"><span class="price-label">';
													echo $this->__('Regular Price'). ': </span>';
													echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p>';
													}
													if($specialprice != '')
													{
													echo '<p class="special-price">
													<span class="price-label">Special Price</span>
													<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
													</p> ';
													} 
													}else {
													echo '<div class="price-boxs">
													<span class="regular-price">
													<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
													</span>    
													</div>';    
													}
													?>
												</div>
											<?php endif; ?>
											<div class="actions clearfix">
												<?php if($addtocart): ?>
													<?php if($_product->isSaleable()): ?>
														<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></button>
													<?php else: ?>
														<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
													<?php endif; ?>
												<?php endif; ?>
												<?php  if($addtowishlist || $addtocompare): ?>
													<ul class="add-to-links">
														<?php if($addtowishlist): ?>
															<?php if ($this->helper('wishlist')->isAllow()) : ?>
																<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist fa fa-heart-o"><em><?php echo $this->__('Add to Wishlist') ?></em></a></li>
															<?php endif; ?>
														<?php endif; ?>
														<?php if($addtocompare): ?>
															<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
																<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare fa fa-bar-chart"><em><?php echo $this->__('Add to Compare') ?></em></a></li>
															<?php endif; ?>
														<?php endif; ?>
													</ul>
												<?php endif; ?>
											</div>
										<?php $i++;?>
										</div>
									</div>
										<?php if($i %$rows == 0) echo "</li>"; ?>                   
									<?php endforeach; ?>
										<?php if($i %$rows != 0) echo "</li>"; ?>
								</ul>	
							</div>
						</div>
					</div>
				</div>
		
			<script type="text/javascript">
				$jq(document).ready(function(){
					<?php $idBx = '#tab'.$cate_id.'-'.$identify.' .owl'; ?>
					$jq("<?php echo $idBx; ?>").owlCarousel({
						autoPlay : false,
						items : <?php if($itemsDefault) echo $itemsDefault; else echo '6'; ?>,
						itemsDesktop : [1560,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
						itemsDesktopSmall : [980,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
						itemsTablet: [768,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
						itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
						slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
						stopOnHover : true,
						pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
						scrollPerPage:true,
					});
				});
			</script>
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 

</div> <!-- #container -->
</div> <!-- #container -->

<script type="text/javascript">

$jq(document).ready(function() {
	
	$jq(".tab_content_<?php echo $identify; ?>").hide();
	$jq(".tab_content_<?php echo $identify; ?>:first").show(); 
	<?php
	if(count($categoryIds) > 1){
	?>
		$jq("ul.tabs<?php echo '-'.$identify;?> li").click(function() {
			$jq("ul.tabs<?php echo '-'.$identify;?> li").removeClass("active");
			$jq(this).addClass("active");
			$jq(".tab_content_<?php echo $identify; ?>").hide();
			var activeTab = $jq(this).find("p").attr('class'); 
			$jq("#"+activeTab).fadeIn(); 
		});
	<?php } ?>
	
});

</script> 
